### ISSUE TITLE
about page on nav no longer links anywhere

### ISSUE THREAD

**Issue by bpizzle** [templesmc/tuupdate#33]

**Comment by astratagem** [comment]
Ah, you really did win. Yeah that's because on touch devices, touching that
link wouldn't just open the submenu, it would also link to the page. So if
someone wanted to get to a subpages it would be difficult. I can look into
alternative solutions or we can move the actual about page to a new submenu
item with a slightly different name.

On Wednesday, September 25, 2013, bpizzle wrote:

> —
> Reply to this email directly or view it on GitHubhttps://github.com/montchr/tuupdate/issues/33
> .

## 

---

_Chris Montgomery_
_This Storm Observatory_
stormobservatory.com
mont.chr@gmail.com

Web Editor
The Temple News
temple-news.com
web@temple-news.com

Web Developer
School of Media and Communication
Temple University
smc.temple.edu
montchr@temple.edu

_Sous les pavés, la plage_.

**Comment by bpizzle** [comment]
hmmmmm

maybe we can link to the site credits on the about page, idk
but i mean i also wanted to add other pages there like 'staff'

**Comment by astratagem** [comment]
You can have all the menu items you want, as long as they aren't on level 0
or level 3+. So if you want a dozen menu items on level 1 (the first
submenu) that is fine. We just have to make sure the single item on level 0
is replaced in the submenu. Make sense? If not, I'll be in shortly.

On Wednesday, September 25, 2013, bpizzle wrote:

> hmmmmm
> 
> maybe we can link to the site credits on the about page, idk
> but i mean i also wanted to add other pages there like 'staff'
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/montchr/tuupdate/issues/33#issuecomment-25086193
> .

## 

---

_Chris Montgomery_
_This Storm Observatory_
stormobservatory.com
mont.chr@gmail.com

Web Editor
The Temple News
temple-news.com
web@temple-news.com

Web Developer
School of Media and Communication
Temple University
smc.temple.edu
montchr@temple.edu

_Sous les pavés, la plage_.
